Decrease timeout and modify benchmark test conditions
Reduced the timeout for integration tests from 60 to 30 minutes and updated the benchmark test condition.

diff --git a/.github/workflows/galata.yml b/.github/workflows/galata.yml
--- a/.github/workflows/galata.yml
+++ b/.github/workflows/galata.yml
@@ -16,7 +16,7 @@ env:
 jobs:
   test:
     name: Integration Tests (${{ matrix.browser }} - ${{ matrix.suite }} ${{ matrix.shard }}/${{ matrix.shards }})
-    timeout-minutes: 60
+    timeout-minutes: 30
     runs-on: ubuntu-22.04
     strategy:
       fail-fast: false
@@ -96,13 +96,22 @@ jobs:
       - name: Test
         run: |
           cd galata
+          set +e  # we want to move the reports even if we fail
           jlpm run test --project ${{ matrix.project }} --shard ${{ matrix.shard }}/${{ matrix.shards }}
           mv test-results/report.json test-results/${{ matrix.browser }}-${{ matrix.project }}-${{ matrix.shard }}.json
+          TEST_EXIT_CODE=$?
 
-          if [[ "${{ matrix.browser }}" == "chromium" ]] && [[ "${{ matrix.project }}" == "jupyterlab" ]] && [[ "${{ matrix.shard }}" == "1" ]]; then
+          BENCHMARK_EXIT_CODE=0
+          if [[ "${{ matrix.browser }}" == "chromium" ]] && [[ "${{ matrix.project }}" == "galata" ]] && [[ "${{ matrix.shard }}" == "1" ]]; then
             # Run benchmark tests once to ensure they have no regressions
             BENCHMARK_NUMBER_SAMPLES=1 jlpm run test:benchmark
+            BENCHMARK_EXIT_CODE=$?
             mv test-results/report.json test-results/benchmark-${{ matrix.browser }}-${{ matrix.project }}-${{ matrix.shard }}.json
+          fi
+
+          # mark as failing
+          if [[ $TEST_EXIT_CODE -ne 0 ]] || [[ $BENCHMARK_EXIT_CODE -ne 0 ]]; then
+            exit 1
           fi
 
       - name: Upload test assets
